name: Variables

on:
  push:
    branches: [main]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: First script from job1
        run: echo Test env var: $OPENAI_API_KEY

